### ISSUE TITLE
[BUG] Send Welcome Intent is sending default error message twice

### ISSUE THREAD

**Issue by PrajvalRaval** [WideChat/Apps.Dialogflow#11]
If we have the `Send Welcome Intent` enabled in the app settings and if the Dialogflow app is not configured properly, then we are getting two default error messages sent to the visitor. Ideally should be only one.

![Screenshot 2020-09-21 at 5 14 26 PM](https://user-images.githubusercontent.com/41849970/93763406-05408b80-fc2f-11ea-8076-09fdce5fff6b.png)

**Comment by shubhsherl** [comment]
@PrajvalRaval I checked this from my side, bot is sending only one error message. The two message you are seeing is from `welcome intent` and from `text message: hi`. Can you check again?

**Comment by PrajvalRaval** [comment]
> @PrajvalRaval I checked this from my side, the bot is sending only one error message. The two messages you are seeing is from `welcome intent` and from `text message: hi`. Can you check again?

I see. Shouldn't we just change that behaviour to include only messages from Welcome Intent? 

For example: If a user writes a random string to initiates a chat session, it will respond with all the messages included in the 'welcome intent' as well as the messages included in the 'fallback intent'. It will be like - 'hey! Welcome, here's all the info we want you to know' accompanied by 'sorry I don't understand you'.

@dlassalle wdyt?

**Comment by dlassalle** [comment]
hopefully we wouldnt see this case too often since we'll be using the open-window session-start trigger, so the welcome event response would ideally appear before the user types their first message.
However in a case where that trigger isnt enabled... im not sure... I think this can remain as an open bug, but the way it functions now might be okay

**Comment by PrajvalRaval** [comment]
> hopefully we wouldnt see this case too often since we'll be using the open-window session-start trigger, so the welcome event response would ideally appear before the user types their first message.
> However in a case where that trigger isnt enabled... im not sure... I think this can remain as an open bug, but the way it functions now might be okay

Yeah, I think if we are removing the part where a visitor has to type something to initiate the session, then this is not really a bug. 👍
