### ISSUE TITLE
[FEATURE] Custom salesforce handoff payload with buttonID support

### ISSUE THREAD

**Issue by dlassalle** [WideChat/Apps.Dialogflow#19]
Allow for a custom payload on DF response that can provide a buttonID (or use the default one in settings if no ID is provided) to trigger a handoff
an example, but not necessarily the format required - that can be more up to the developer about what is best
```
{
  "action": "LiveAgentHandoff",
  "params": {
    "buttonId": "some_id_1234"
  }
}
```

**Comment by Shailesh351** [comment]
@dlassalle We have handoff support using quickReplies https://github.com/WideChat/Apps.Dialogflow/blob/master/docs/QuickReplies.md. which shows buttons and when user clicks button handoff is performed. 

As per my understanding, here we need handoff feature without showing and clicking button, so we add this payload in DF response and handover will be performed without user interaction. Is this correct? Let me know if I'm thinking in wrong direction.

**Comment by dlassalle** [comment]
@Shailesh351 yes thats correct
