### ISSUE TITLE
[FEATURE] Multiple bot configs in App settings

### ISSUE THREAD

**Issue by dlassalle** [WideChat/Apps.Dialogflow#7]
When testing out multiple bot environments, its useful to be able to quickly switch between them.
Make the values
- Project Id
- Client Email
- Private Key
- Environment
into a group that we can add multiple of, then be able to select a group to be the active bot via a drop down or some other mechanism

**Comment by shubhsherl** [comment]
@dlassalle How many bots you want to add? I don't think RC-apps allows us to add setting fields dynamically.

**Comment by dlassalle** [comment]
@shubhsherl :( in that case, lets try starting with two and we can re-visit the dynamic portion some other time

**Comment by shubhsherl** [comment]
@dlassalle If this is only for testing purposes, we can also do it by adding value in respective fields separated by a comma.
Like:
project number to use: Int
project ID: <projID 1>,<projID 2>
client email: <proj 1's client email>,<proj 2's client email>
