### ISSUE TITLE
[FEATURE] Optional welcome message along with welcome event

### ISSUE THREAD

**Issue by dlassalle** [WideChat/Apps.Dialogflow#8]
When using the livechat trigger 'Visitor opens chat window' with 'Start session' action, it would be nice if the first thing that popped up was a message saying something like 'Thank you for contacting Viasat!' prior to the welcome event firing.

Add a config option in the app settings to allow a session-start text to be added, so the user immediately sees the text rather than waiting for the welcome event to finish

**Comment by shubhsherl** [comment]
@dlassalle I believe that we can do it by creating another trigger with 'open-chat-window' condition, and 'send-message' action.

**Comment by shubhsherl** [comment]
@dlassalle There was an issue in open-chat-window, which I fixed [here](https://github.com/WideChat/Rocket.Chat.Livechat/pull/32), so please test the above method after you merge this PR. Thanks.

**Comment by dlassalle** [comment]
@shubhsherl That does seem to work, but is there a way we can make it have a blank icon, or set it to look like the bot is saying it?
if i impersonate the next from queue, sometimes its the liveagent user and not the bot
if i use a 'custom agent' Virtual Assistant, it gives me the default 'V' icon

**Comment by shubhsherl** [comment]
@dlassalle There is an option in Routing `Assign new conversations to bot agent`(in routing section of omnichannel). Is it assigning to agent even after enabling that option?

**Comment by dlassalle** [comment]
@shubhsherl Yes it does, since the liveagent user that is used to connect to salesforce is also a bot
